steps:
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ['--version']
#   - name: maven:3-jdk-8
#     entrypoint: mvn
#     args: ['test']
spec:
  containerConcurrency: 80
  timeoutSeconds: 300
  containers:
  - image: us.gcr.io/project-test/express-image:1.0
    ports:
    - name: http1
      containerPort: 8080
    resources:
      limits:
        memory: 256Mi
        cpu: 1000m 
